# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/daria/zahedan/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    cam_vpu1 \
    cam_vpu2 \
    cam_vpu3 \
    dpm \
    gz \
    lk \
    mcupm \
    md1img \
    pi_img \
    preloader \
    scp \
    spmfw \
    sspm \
    tee
